# Debian packages we want (makes life better);
#
# - asciidoctor
# - cmake
# - libmbedtls-dev
# - ninja-build
# - clang
# - clang-format
# - gcc (-7?)
# - g++ (-7?)
#
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: apt-get update -qq && apt-get install -y build-essential asciidoctor cmake libmbedtls-dev ninja-build clang clang-format
      - run:
          name: Configure
          command: mkdir build && cd build && cmake -DNNG_TRANSPORT_TLS=ON -G Ninja ..

      - run:
          name: Build
          command: cd build && ninja

      - run:
          name: Run Tests
          command: cd build && ninja test

#      - run:
#          name: Check Format
#          command: ./etc/format-check.sh
